RULE_NOT_VALID = "Rule is not valid"
RULE_MATCH_TYPE_NOT_SUPPORTED = "Rule match type is not supported"
RULE_DATA_NOT_VALID = "Rule data is not valid"
SDK_OR_DATA_OBJECT_REQUIRED = "SDK key or Data object should be provided"
DATA_OBJECT_MISSING = "Data object is missing"
VISITOR_ID_REQUIRED = "Visitor string string is not present"
GOAL_DATA_NOT_VALID = "GoalData object is not valid"
